"""
Django settings for personal project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=l^g7k!(0z6rm9$yc)phhi5g!ou3(zxhyo@vjj!icp$r!78n)j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

TIME_ZONE = 'Europe/Istanbul'  # Yerel saat dilimi olarak İstanbul'u seçiyoruz
USE_TZ = True  # Zaman dilimi desteğini etkinleştiriyoruz
# Application definition
STATIC_URL = '/static/'
# settings.py
AUTH_USER_MODEL = 'personal_track.Employee'

# Statik dosyaların fiziksel dizini
STATICFILES_DIRS = [
    BASE_DIR / "/static",  # Projenizin kök dizinindeki 'static' klasörü
]
ASGI_APPLICATION = 'personal.asgi.application'
WEBSOCKET_URL = '/ws/'  # WebSocket URL'si
# Kanal Katman Konfigürasyonu (Redis kullanımı önerilir)
# Channels ayarları
ASGI_APPLICATION = 'personal.asgi.application'

# Redis ayarları
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],  # Redis'in çalıştığı adres ve port
#         },
#     },
# }
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Bu örnek, InMemoryChannelLayer'ı kullanır
    },
}
# Uygulama içindeki statik dosyaların yolu
STATIC_ROOT = BASE_DIR / "staticfiles"  # 'collectstatic' komutuyla bu dizine kopyalanır
INSTALLED_APPS = [
    'faker',
    'drf_yasg',
    'daphne',
    'rest_framework',
    'personal_track',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Bunu ekleyin
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Celery için broker (Redis kullanılıyor, alternatif olarak RabbitMQ da kullanılabilir)
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis, Docker veya sistemde çalışıyorsa

# Celery sonuçları (opsiyonel, ihtiyacınıza göre)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

ROOT_URLCONF = 'personal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'personal_track.context_processors.pending_leave_requests',
                'personal_track.context_processors.today',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'personal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'personal',  # Veritabanı adınız
        'USER': 'postgres',  # PostgreSQL kullanıcı adınız
        'PASSWORD': 'serkan',  # PostgreSQL şifreniz
        'HOST': 'localhost',  # Genellikle localhost olur
        'PORT': '5432',  # PostgreSQL varsayılan portu
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
